### PR TITLE
Responsive 600

### LINKED ISSUE #29: Media Query - max-width: 600px
Make site responsive at 600px screen size

### PR DESCRIPTION
**Pull request by ashlynn-cleveland**
I finished writing all of the media queries for a screen size of 600px. However, I made a change outside of the media queries on line 22. I commented out the width of .container because the content was overflowing at smaller screen sizes.

### CODE REVIEW

**Comment by ashlynn-cleveland** [comment]
Would someone like to review the code before I merge?

**Comment by ashlynn-cleveland** [comment]
I linked the max-width: 480px issue as well because it looks like the media queries work at 480px too

**Comment by ashlynn-cleveland** [comment]
Never mind, I found something :')

**Comment by AlainPicard0x0** [comment]
FYI, I usually just add .container width: 100% to my media queries. That way the .container class can keep it's properties at larger screen sizes.

**Comment by ashlynn-cleveland** [comment]
I didn't use width 100% in this case because the margin is set to auto. Adding a width of 100% pushes the margin outside of the viewport boundaries and distorts the content. Having the margin set to auto should automatically center the content the page and maintain the content's appearance on all screen sizes.

**Pull request merged**
